
modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="sworddisplay"
version="${file.jarVersion}"
displayName="Sword Displays"
updateJSONURL="https://github.com/sokratis12GR/Sword-Displays"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sword-displays"
logoFile="logo.png"
authors="SoFoDev"
description='''
    Allows the user to display their swords via the use of a sword display block.
'''
[[dependencies.sworddisplay]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.sworddisplay]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
